version: '3.0'

services:
  mysql:
    image: mysql/mysql-server:8.0.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=nova
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ecoin
    ports:
      - "3306:3306"

  ecoinbe:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - mysql
    env_file:
      - .env
    restart: unless-stopped